### ISSUE TITLE
Test Website on Multiple Browsers

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#10]
**Description:** To guarantee a seamless user experience for all, we need to verify that our website performs flawlessly on a variety of web browsers. This includes popular options like Chrome, Firefox, Safari, and Edge. We're looking for contributors to conduct thorough testing and report any compatibility issues they encounter. Your efforts will help us ensure universal accessibility.

- **Difficulty:** Easy

- **Tags:** Testing, Compatibility, Browsers

**Comment by dipteshrastogi** [comment]
sir, may I be assigned this issue, please?
I want to work on it

**Comment by IshaanAdarsh** [comment]
@visheshrwl I can assign this issue to you if you comment on this. I am going through your PR right now and will look at the changes ASAP

**Comment by visheshrwl** [comment]
> @visheshrwl I can assign this issue to you if you comment on this. I am going through your PR right now and will look at the changes ASAP

@IshaanAdarsh /assign
