### ISSUE TITLE
`To Professor` Link Not Working

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#100]
**Problem:** The link for "To Professor" in the footer is currently non-functional. It is directed to an invalid URL 'pro.'
- **Solution:** Update the 'href' attribute for the "To Professor" link to "prof" to ensure it directs users to the correct professor's page.

**Comment by anevski-stefan** [comment]
@IshaanAdarsh Can you please assign me, i want to work on this issue

**Comment by anevski-stefan** [comment]
It's done, can you please review it?
