### ISSUE TITLE
`About` Link Not Functioning

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#102]
**Problem:** The link for "About" in the footer is not functioning correctly. It directs users to an invalid URL 'bout.'
- **Solution:** Adjust the 'href' attribute for the "About" link to "about" to ensure that users can access the about page as intended.

**Comment by 12345rams** [comment]
assign me

**Comment by architgupta435** [comment]
Can you please assign this issue to me .
