### ISSUE TITLE
Expanding Our Reach: Translating Website Content to Hindi

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#11]
**Description:** In our quest to reach a broader audience, we're embarking on the journey of translating our website content into Hindi. We're seeking dedicated contributors who can deliver accurate translations while maintaining consistency in tone and style. This initiative will make our content accessible and engaging to Hindi-speaking users.

- **Difficulty:** Medium

- **Tags:** Localization, Translation

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh could you please assign this issue to me?

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Could you please merge my PR so that I can start working on the next issue?

**Comment by IshaanAdarsh** [comment]
@Pranav-Rustagi I wanted to ask you if your could change the UI of the Choose language section for the Google API. TO match with the ezmails UI.

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Sure, I can do that. Should I create a new issue? If you do, please assign me the task.

**Comment by IshaanAdarsh** [comment]
> @IshaanAdarsh Sure, I can do that. Should I create a new issue? If you do, please assign me the task.

Yup go ahead, if you find any more issues you can also open more issues. They will be assigned according to your preference
