### ISSUE TITLE
Enhance Sign-In Page UI

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#112]
**Description:** The current sign-in page could benefit from improved user interface design to make the login process more user-friendly and visually appealing. This includes optimizing the layout, enhancing input fields, and ensuring a smooth user experience.
- **Tasks:**
    - Redesign the sign-in form layout for better user flow.
    - Improve the styling of input fields, buttons, and other UI elements.
    - Implement responsive design for various screen sizes.
- **Labels:** UI Enhancement, Sign-In Page, User Experience
- **Milestone:** UI Improvement

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by supunvindula** [comment]
Please add **hacktoberfest-accepted** label if you can. Thank you!

**Comment by IshaanAdarsh** [comment]
As soon as you make the PR i will add the hacktoberfest accepted tag to your accepted PR.

**Comment by avelynhc** [comment]
@IshaanAdarsh Hi, can I work on this? Thanks!

**Comment by avelynhc** [comment]
Hi, I changed a bit as below. Current css applies to various screen sizes. Are there specific changes you want to make to the sign-in and sign-up page? Please let me know. Thanks!

<img width="463" alt="Screenshot 2023-10-31 at 2 09 18 PM" src="https://github.com/IshaanAdarsh/ezmail/assets/75185537/6b9354d4-29a3-4092-a69a-9ce9aeab252b">
<img width="470" alt="Screenshot 2023-10-31 at 2 09 27 PM" src="https://github.com/IshaanAdarsh/ezmail/assets/75185537/4bfe86f8-e609-47e2-91f5-dafc17663dfe">

**Comment by IshaanAdarsh** [comment]
Looks good @avelynhc. Make a PR and i'll merge it
