### ISSUE TITLE
Bug : Wrong Text Alignment inside mailing app (outlook)

### ISSUE THREAD

**Issue by SanskarSonwani** [IshaanAdarsh/ezmail#117]
The whole Email text (including different paragraphs) appear in a single line in the mailing app. The mail text should appear as its shown on the ezmail's site.

**To Reproduce**
1. Go to Alumni and Strangers section 
2. Click on Request for alumni networking opportunities
3. Click on Send Email
4. See the error in the mailing app's window

**Expected behavior**
The mail should come in the same alignment as it is shown in Ezmail.

**Screenshots**
<img width="807" alt="Screenshot 2023-11-10 124048" src="https://github.com/IshaanAdarsh/ezmail/assets/113914564/58dda521-f788-40f5-9d79-d3b264c7fad9">

<img width="700" alt="Screenshot 2023-11-10 124036" src="https://github.com/IshaanAdarsh/ezmail/assets/113914564/9bb96c0d-d9f7-45ff-96da-b541d950fff4">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Microsoft Edge

**Comment by IshaanAdarsh** [comment]
@SanskarSonwani if you want to work in this go ahead.
