### ISSUE TITLE
Improvement: Enhance UI of About Us Section on the Website

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#124]
## Description
The current UI of the "About Us" section on our website could benefit from some improvements to enhance user experience and visual appeal. This issue is created to track and address the necessary enhancements in the UI design of this section.

## Current UI Pain Points
- [ ] Lack of visual hierarchy.
- [ ] Text and images not well-aligned.
- [ ] Limited use of engaging elements.
- [ ] Inconsistencies in color scheme and typography.

## Proposed Changes
- [ ] Establish a clear visual hierarchy to guide users through the content.
- [ ] Ensure proper alignment of text and images for a cleaner look.
- [ ] Introduce visually engaging elements to make the section more appealing.
- [ ] Harmonize the color scheme and typography for consistency.

## Additional Information
Feel free to provide additional context, ideas, or suggestions that could contribute to the improvement of the "About Us" section. Screenshots, if available, would be helpful for a better understanding of the current state.

## Acceptance Criteria
- [ ] The UI changes should enhance the overall aesthetics and usability.
- [ ] The improvements should be consistent with the overall design language of the website.

<img width="1360" alt="Screenshot 2023-12-13 at 5 29 31 PM" src="https://github.com/IshaanAdarsh/ezmail/assets/100434702/7a242350-aaeb-44c5-b394-a6c741721dde">

**Comment by ayann07** [comment]
I would like to work on this issue under kharagpur winter of code.

**Comment by mendacium-a11y** [comment]
is this still open to work on, because my fix is almost done?

**Comment by ayann07** [comment]
Is it opened ? Sorry for being inactive, if it is opened then I can work on this

**Comment by IshaanAdarsh** [comment]
Yes, there was some issue with the pull request.

**Comment by ayann07** [comment]
Okay , I will work on this now.
