### ISSUE TITLE
Ishan's avatar not visible on Our Team section

### ISSUE THREAD

**Issue by mendacium-a11y** [IshaanAdarsh/ezmail#134]
**Describe the bug**
Ishaan's avatar is not visible in the Our Team section on the main page

**To Reproduce**
1. Go to https://ezmail-home.vercel.app/
2. Scroll down to 'Our Team'

**Expected behavior**
Both the avatars should be visible, and if the img fails to load, there should be a placeholder so that the placement of other elements isnt affected

**Browsers**
1 Firefox
2 Chrome
3 Brave

**Screenshots**
current prod
![Screenshot 2023-12-18 at 23-40-56 https __ezmail-home vercel app](https://github.com/IshaanAdarsh/ezmail/assets/110321699/3c3171dc-ec0c-44c8-a909-4337819e5c27)

proposed solution

![sol](https://github.com/IshaanAdarsh/ezmail/assets/110321699/e30a7f86-7a9f-463a-8d21-bd46a58e33a1)

**Comment by IshaanAdarsh** [comment]
@mendacium-a11y would you like to work on this.

**Comment by mendacium-a11y** [comment]
yes please
