### ISSUE TITLE
Review and Update Website Content

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#14]
**Description:** Keep the website's content fresh and accurate by reviewing and updating outdated information. Contributors can check pages for outdated content and make necessary updates.

- Difficulty: Easy
- Tags: Content, Updates

**Comment by prokaushik** [comment]
I can do it well.

**Comment by SanidhayaAgarwal** [comment]
Hello @IshaanAdarsh ,

I'm excited to participate in Hacktoberfest and contribute to this repository. Please consider me for this issue. I look forward to collaborating with the community.

Thank you!

**Comment by SanidhayaAgarwal** [comment]
@IshaanAdarsh can you please provide me with the link

**Comment by IshaanAdarsh** [comment]
@SanidhayaAgarwal basically you have to update the information in the About page.

The content of the About page is not very concise making it very long to read and understand. So I want to make it more readable, so information about this website is relayed more easily.
