### ISSUE TITLE
Correct Typos in Website Text

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#15]
**Description:** Improve the website's professionalism by fixing any typos or spelling errors in the text content. Contributors can review pages and make corrections.

- Difficulty: Very Easy
- Tags: Proofreading, Text

**Comment by bhalerao-2002** [comment]
Hello @IshaanAdarsh, 
If you assign me any of the issues, I have to go through all the code and content so I also want to work on typos, as it will lead to a Win-Win for us, I will complete my Hactoberfest PR count easily.
Please assign me this under Hacktoberfest 2023. :)

**Comment by ashmitsinghk** [comment]
Hi @IshaanAdarsh! I would like to work on this issue, kindly assign it to me :)

**Comment by IshaanAdarsh** [comment]
https://github.com/IshaanAdarsh/ezmail/pull/41
