### ISSUE TITLE
Add "Privacy Policy" and "Terms of Service" Pages

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#16]
**Description:** Ensure legal compliance, transparency, and address privacy concerns by adding both a "Privacy Policy" and a "Terms of Service" page to the website. Contributors can create basic documents for both pages to provide clear guidelines to users.

- **Difficulty:** Easy

- **Tags:** Privacy, Legal, Terms of Service

**Comment by ayushman075** [comment]
I want to work on this @IshaanAdarsh sir pls assign me this issue

**Comment by IshaanAdarsh** [comment]
@ayushman075 how much of the work is pending could you give an update on it.

**Comment by ayann07** [comment]
Hey, I would like to work for this under KWOC 2023. But before I begin to contribute, just tell me where are these details given of the website, like from where I have to check or I have to write the privacy policy and terms of service all by own?

**Comment by IshaanAdarsh** [comment]
> Hey, I would like to work for this under KWOC 2023. But before I begin to contribute, just tell me where are these details given of the website, like from where I have to check or I have to write the privacy policy and terms of service all by own?

Just right a boiler plate content for these pages.if there are any issues I will request the changes myself.

Attach them in the footer.
