### ISSUE TITLE
Add Contact Information

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#17]
**Description:** Improve user accessibility by adding a "Contact Us" section to the website. Include a contact form or provide clear contact details for users to reach out with inquiries or feedback.

- **Difficulty:** Easy

- **Tags:** Accessibility, Contact, User Communication

**Comment by bhalerao-2002** [comment]
Hi @IshaanAdarsh , 
Yes **Contact Us** is a must-section for Marketplace, As the whole point is to collect customers.
I understand your Concern. I will suggest that to do both, But firstly it is more important to add your clear information, after that the Feedback/ Contact/ Enquiry Form.
Please assign me this issue as I am working on your code I will alter most of the things.
Assign me under Hacktoberfest.
