### ISSUE TITLE
Update Website Footer

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#18]
**Describe the bug**
Improve the footer section of the page

**To Reproduce**
1. Go to 'ezmail.vercel.app'
2. Scroll Down to the footer
3. Notice the links section of the footer

**Difficulty** 
Medium

**Expected behavior**
Move the links section to the right side of the page while keeping the page reponsive

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/314f27a5-3be3-4ce3-8ccd-44cdf0fb6ff3)

**Comment by bhalerao-2002** [comment]
Hello @IshaanAdarsh, I have gone through your code, and I understand your problem. 😊
I want to work on it, I will try my best to match the vibe.
assign me this issue under Hacktoberfest 2023 :)
Happy Developing

**Comment by IshaanAdarsh** [comment]
Hello @bhalerao-2002,
Start working on the footer, this is a more challenging task, If you can complete this I will assign you the other tasks as well. We can't hold up tasks by assigning them to a singular person.

**Comment by IshaanAdarsh** [comment]
@bhalerao-2002 are you still working on this.

**Comment by bhalerao-2002** [comment]
Yes, I am Working on. Trying to animate the footer, but as the website is not Positioned ideally, I am fixing my methods.
Soon I will raise my PR
Thank You for patience @IshaanAdarsh

**Comment by IshaanAdarsh** [comment]
> Yes, I am Working on. Trying to animate the footer, but as the website is not Positioned ideally, I am fixing my methods.
> Soon I will raise my PR
> Thank You for patience @IshaanAdarsh

Okay, great.

**Comment by Smit1610** [comment]
@IshaanAdarsh Can you assign me other task ?

**Comment by Albert-2** [comment]
got you kindly assign me this issue...
THANK YOU...!!:)

**Comment by Albert-2** [comment]
hey @IshaanAdarsh 
first of all thank you to assign me this issue and frankly speaking that UI man 🔥
i have made requested changes please verify it and tell me if you want any further assistance
THANK YOU...!!:)

**Comment by IshaanAdarsh** [comment]
@Albert-2 there are some conflicts with the main branch. Make the changes and i will review the PR
