### ISSUE TITLE
Fix Image URL to Prevent Caching

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#20]
**Description**: The image in the top left corner of the site is currently linked with an absolute URL. To prevent caching and ensure it remains accessible, consider using a relative URL that points to the `ezmail.png` file in the `static` directory.

- **Difficulty**: Low
- **Tags**: Bug, Website, Image, URL

**Comment by DaSeeker67** [comment]
Please assign this to me

**Comment by dipteshrastogi** [comment]
sir, please assign this to me 
I want to work upon it

**Comment by One2sahu** [comment]
I want to work on this problem please assign me this issue. please!!

**Comment by IshaanAdarsh** [comment]
@One2sahu any progress on solving this issue?

**Comment by One2sahu** [comment]
Sorry sir We have Mid semaster exams from Monday that's why I didn't do
any  significant  thing to resolving this issue. I'll be back in work after
mid sem.

**Comment by Jilesh980** [comment]
Hi Ishaan it looks pretty good to make URL relative for better web application, i am looking forward to work on this issue, please assign me under hacktoberfest. Thank you

**Comment by agnik06** [comment]
Hi Ishaan, I am new to open source contribution could you assign me this issue to work on.
