### ISSUE TITLE
Add Contributors Section

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#21]
**Description**:Consider adding a dedicated section in the about page to acknowledge and credit all contributors to the project. This can foster a sense of community and appreciation among contributors.
- Difficulty: Medium
- Tags: Community, Contributors

**Comment by ani-netizen** [comment]
> **Description**:Consider adding a dedicated section in the about page to acknowledge and credit all contributors to the project. This can foster a sense of community and appreciation among contributors.
> 
> * Difficulty: Medium
> * Tags: Community, Contributors

Hey @IshaanAdarsh 
I can do this task please share some contributors to add

**Comment by ani-netizen** [comment]
@IshaanAdarsh please share details of contributors that need to be added 

1. Profile pic
2. Name 
3. GitHub id (linked with their profile)
These are the few things that will be there if there are any changes do let me know and share details of contributors

**Comment by IshaanAdarsh** [comment]
@ani-netizen I need it to be updated continuously. Maybe some connection with the GitHub can achieve that. I don't want you to enter the details manually everytime.

Like you just contributed to the repo, this should be showcased in the section.

**Comment by ani-netizen** [comment]
> @ani-netizen I need it to be updated continuously. Maybe some connection with the GitHub can achieve that. I don't want you to enter the details manually everytime.
> 
> Like you just contributed to the repo, this should be showcased in the section.

So do you know some packages or API we can use or we need to find it

**Comment by ani-netizen** [comment]
> @IshaanAdarsh please share details of contributors that need to be added
> 
> 1. Profile pic
> 2. Name
> 3. GitHub id (linked with their profile)
>    These are the few things that will be there if there are any changes do let me know and share details of contributors

Hey @IshaanAdarsh please confirm on this 
Also can you tell the position where you want the contributors section 
![image](https://github.com/IshaanAdarsh/ezmail/assets/83304810/e24c825a-f023-455a-a0ef-9e761bd81834)
I was thinking to add it here i.e. between tech stack and navigating problems please share you insights so that I can complete the task soon

**Comment by IshaanAdarsh** [comment]
@ani-netizen yes that space is a good point for a contributor section. get started on the task.

**Comment by ani-netizen** [comment]
> @ani-netizen yes that space is a good point for a contributor section. get started on the task ASAP

Carousel or grid

**Comment by IshaanAdarsh** [comment]
Carousel

**Comment by ani-netizen** [comment]
Hey @IshaanAdarsh 

Sorry for the delay
I have completed the task and sent a request #81, kindly review it 
Thank you

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Please close the issue
