### ISSUE TITLE
Make the Our Team section responsive 

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#24]
## Describe the bug
The our team section of the homepage is not responsive for smaller screens

To Reproduce

1. Go to 'ezmail.vercel.app/'
2. Scroll Down to the our team section
3. Open inspect tools and observe for different screen sizes

**Difficulty**
Medium

## Expected behavior
Make the section responsive to all screens

## Screenshots
![image](https://github.com/nown1ne/ezmail/assets/25835195/93560077-00b6-496c-b83f-57eab0c01a21)
![image](https://github.com/nown1ne/ezmail/assets/25835195/5ed144dc-89e6-40b8-9ccb-75c946f32f98)

**Comment by Ahnaf-codes** [comment]
hey @IshaanAdarsh I am eager to help. You can assign me

**Comment by Sudhanshu2306** [comment]
hello @IshaanAdarsh sir, I want to work on this issue, please assign me this
