### ISSUE TITLE
Make the Professor section responsive 

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#25]
**Describe the bug**
The prof section of the website is not responsive for smaller screens 

**To Reproduce**
1. Go to 'ezmail.vercel.app/prof'
2. Open inspect tools and observe for different screen sizes

**Difficulty** 
Medium

**Expected behavior**
Make the template grid responsive for all screens to imrpove readability of the website

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/78603e8e-bba3-45f8-9b0b-378386f78878)
![image](https://github.com/nown1ne/ezmail/assets/25835195/851bad90-8df2-432b-b4d5-6fceb507f9d5)

**Comment by IrfanshaikH-7** [comment]
Hello! I have looked into it - and I'd like to work on it. can you assign it to me so I could start working on it.

thank you

**Comment by IrfanshaikH-7** [comment]
Great - thanks

**Comment by IrfanshaikH-7** [comment]
Hello !
could you please change the file name "static/favicon.png:Zone.Identifier" , just remove the double colon in them. because there is an issue with filename containing colon, and I'm not able to clone.
although I did manage to bypass it but the working tree is a mess...

**Comment by IrfanshaikH-7** [comment]
@IshaanAdarsh  Hello! I resolved the issue! but i find that the web app is broken ! and routes are messed up! i do fixed a typo on links that was href="/pro" when it should be href="/prof" -did someone changed it accedently ?

**Comment by IshaanAdarsh** [comment]
> @IshaanAdarsh Hello! I resolved the issue! but i find that the web app is broken ! and routes are messed up! i do fixed a typo on links that was href="/pro" when it should be href="/prof" -did someone changed it accedently ?

That is another issue we have #13, we have just created that to get someone started on ezmail

**Comment by IshaanAdarsh** [comment]
> is Its okay if I PR the code on 1st oct.
> and I'd like to make all the routes responsive.so can you assign me all the issues regarding UI modifing and responsiveness

Totally get it, i was just going to say start Pr;s form the 1st

**Comment by IshaanAdarsh** [comment]
> Great!
> and thank you for the great opportunity this is the my first Opensource contribution.
> and could you assign me all the responsiveness issues.

I can assign you one more responsive issue. Like you there are a lot of people struggling with open source, these simple problems can give them a headstart and assigning you more issues will limit their reach. Also do star the project so it can reach more people

**Comment by IrfanshaikH-7** [comment]
Oh right! I haven't thought about it! and Thank you

**Comment by DaSeeker67** [comment]
Please assign it to me if required

**Comment by IshaanAdarsh** [comment]
> Please assign it to me if required

PR is already done @DaSeeker67, you could pick another issue
