### ISSUE TITLE
Make the features section responsive

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#26]
**Describe the bug**
Make the features grid responsive

**To Reproduce**
1. Go to 'ezmail.vercel.app'
2. Scroll down to the features section
3. Open inspect tools and observe for different screen sizes

**Difficulty** 
Medium

**Expected behavior**
The features grid should adjust as per the screen size to allow for easy reading and comfortable reading.

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/abd6ac3a-8cfd-4da5-b225-7f4766837521)
![image](https://github.com/nown1ne/ezmail/assets/25835195/fdec68f0-1702-4756-8465-0b8d3b29c4f6)

**Comment by nown1ne** [comment]
Try using a mobile device instead of developer tools.
Check if you can replicate the issue.

**Comment by ani-netizen** [comment]
> @ani-netizen try using a mobile device instead of developer tools. Check if you can replicate the issue.

Thanks for the help I was able to replicate the issue and locate it you can assign this to me

**Comment by ani-netizen** [comment]
PS D:\> 
>> git clone https://github.com/ani-netizen/ezmail.git
>> 
Cloning into 'ezmail'...
remote: Enumerating objects: 241, done.
remote: Counting objects: 100% (241/241), done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 241 (delta 114), reused 130 (delta 46), pack-reused 0R
iB | 111.00 KiB/s
Receiving objects: 100% (241/241), 162.60 KiB | 173.00 KiB/s, done.
Resolving deltas: 100% (114/114), done.
**_error: invalid path 'static/favicon.png:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed._**
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

PS D:\> 
>> cd ezmail
>> 
PS D:\ezmail> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    .github/ISSUE_TEMPLATE/bug_report.md
        deleted:    .github/ISSUE_TEMPLATE/feature_request.md
        deleted:    .gitignore
        deleted:    .npmrc
        deleted:    CODE_OF_CONDUCT.md
        deleted:    CONTRIBUTING.md
        deleted:    Content/Email to Administration.md
        deleted:    Content/To Alumni.md
        deleted:    Content/To Professor.md
        deleted:    README.md
        deleted:    package-lock.json
        deleted:    package.json
        deleted:    postcss.config.cjs
        deleted:    src/app.css
        deleted:    src/app.html
        deleted:    src/click_outside.js
        deleted:    src/components/trans.svelte
        deleted:    src/routes/+error.svelte
        deleted:    src/routes/+layout.svelte
        deleted:    src/routes/+page.svelte
        deleted:    src/routes/about/+page.svelte
        deleted:    src/routes/admin/+page.server.js
        deleted:    src/routes/admin/+page.svelte
        deleted:    src/routes/admin/[slug]/+page.server.js
        deleted:    src/routes/admin/[slug]/+page.svelte
        deleted:    src/routes/admin/data.js
        deleted:    src/routes/others/+page.server.js
        deleted:    src/routes/others/+page.svelte
        deleted:    src/routes/others/[slug]/+page.server.js
        deleted:    src/routes/others/[slug]/+page.svelte
        deleted:    src/routes/others/data.js
        deleted:    src/routes/prof/+page.server.js
        deleted:    src/routes/prof/+page.svelte
        deleted:    src/routes/prof/[slug]/+page.server.js
        deleted:    src/routes/prof/[slug]/+page.svelte
        deleted:    src/routes/prof/data.js
        deleted:    static/ezmail.png
        deleted:    static/favicon.png
        deleted:    static/favicon.png:Zone.Identifier
        deleted:    svelte.config.js
        deleted:    tailwind.config.cjs
        deleted:    vite.config.js

PS D:\ezmail> git restore --source=HEAD :/
error: invalid path 'static/favicon.png:Zone.Identifier'
PS D:\ezmail>


@IshaanAdarsh can you help me with this
