### ISSUE TITLE
Center the Input and Button 

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#27]
**Describe the bug**
Center the input field and button in the email viewing page of others section

**To Reproduce**
1. Go to 'ezmail.vercel.app/others'
2. Click on any of the templates
3. Notice the input and buttons

**Difficulty** 
Medium

**Expected behavior**
Center the input and bbutton while keeping the page responsive

**Screenshots**
![image](https://github.com/nown1ne/ezmail/assets/25835195/0011de47-1ca6-4898-ba27-4700314317e3)

**Comment by yashwanthvarma18** [comment]
Hello @IshaanAdarsh , I'm eager to contribute. Please assign me

**Comment by Ahnaf-codes** [comment]
hey @IshaanAdarsh I'd be willing to work on this. I am fairly experienced working on responsive issues. you can expect a pr soon if you assign me

**Comment by harshk461** [comment]
Hey @IshaanAdarsh i want to work on this project

**Comment by yashwanthvarma18** [comment]
hey  @IshaanAdarsh i dont know how it got unassigned i completed the work please assign me again

**Comment by Sudhanshu2306** [comment]
hello @IshaanAdarsh sir, please assign me this issue

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh The issue has been resolved and is not present in the current version. You can close the PR.
