### ISSUE TITLE
Improve the Hamburger Menu

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#28]
The current hamburger menu on our website doesn't blend seamlessly with our design language, creating a visual inconsistency. This issue aims to enhance the hamburger menu's design to ensure it aligns harmoniously with the overall website design.

Difficulty - Hard
Tags - Enhancement, UI/UX, Design

**Comment by MacMillon-VS** [comment]
I'd like to work on enhancing the hamburger menu's design, Could you please consider assigning this task to me?
