### ISSUE TITLE
The Get started page  have responsiveness issues

### ISSUE THREAD

**Issue by DaSeeker67** [IshaanAdarsh/ezmail#44]
The get started page of the Ezmail have many request tabs but since they have some minor issues with text wraping in small screen 

1. Go to https://ezmail-home.vercel.app/prof
2. Click on Get Started
3. See error

The divs should be arranged vertically so that text can easily be seen to the users 

![image](https://github.com/IshaanAdarsh/ezmail/assets/65525769/8fb8e7ef-daed-49c6-a792-d1c3d16a1e3e)

**Smartphone ):**
 - Device: iphonex
 - OS: ios16
 - Browser safari

I would love to resolve this issue, Please assign it to me

**Comment by IshaanAdarsh** [comment]
Issue already opened in #25.
i can assign you that issue
