### ISSUE TITLE
Improve Hamburger Menu UI to Match Site Design

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#45]
**Issue Description:**
The current design of the hamburger menu on the website does not align with the overall design aesthetics of the site. It appears inconsistent and affects the user experience. This issue is raised to enhance the UI of the hamburger menu to match the site's design language seamlessly.

**Steps to Reproduce:**
1. Visit the website.
2. Observe the hamburger menu's design and appearance.
3. Compare it to the site's overall design.

**Expected Behavior:**
The hamburger menu should be visually consistent with the site's design, ensuring a cohesive and pleasing user experience.

**Actual Behavior:**
The current hamburger menu design appears inconsistent with the site's overall design.

**Additional Information:**
A cohesive and visually appealing UI enhances the overall user experience, making navigation more intuitive and engaging.

**Proposed Changes:**
1. Analyze the website's design language.
2. Redesign the hamburger menu to match the overall design aesthetics.
3. Ensure that the new design maintains responsiveness for different devices.

https://github.com/IshaanAdarsh/ezmail/assets/93966956/e5d7e536-610e-44eb-8d7c-afabfe4c2d3d

**Comment by shrutiiigupta** [comment]
What do you want exactly? Like do you want that hamburger to pop up or like can you explian this?/

**Comment by IshaanAdarsh** [comment]
the hamburger menu is not the issue. The design of the menu is very off-putting and doesn’t go well with the basic design of the site (colour and theme). So just to make a homogeneous site, we will need a better aligned menu

**Comment by shrutiiigupta** [comment]
Okayy, Assign this to me, I'll do it

**Comment by shrutiiigupta** [comment]
can you assign this to me under hacktoberfest?
