### ISSUE TITLE
Set Up Security Policy for ezmail Repository

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#48]
**Issue Description:**
Create a `SECURITY.md` To ensure the security and integrity of the ezmail repository, it's essential to establish a comprehensive security policy. This policy will outline guidelines, best practices, and measures to safeguard the codebase, user data, and the project as a whole.

**Proposed Security Measures:**
1. **Code Scanning:** Implement code scanning tools to identify and address vulnerabilities in the source code.
2. **Dependency Scanning:** Regularly check and update project dependencies to patch known security vulnerabilities.
3. **Access Control:** Define and enforce access control policies to restrict repository access to authorized contributors only.
4. **Regular Audits:** Conduct security audits and assessments to identify and mitigate risks proactively.
5. **Reporting Vulnerabilities:** Establish a process for reporting and addressing security vulnerabilities responsibly.
6. **Security Documentation:** Create documentation outlining security best practices for contributors.
7. **Incident Response Plan:** Develop a plan to handle security incidents and breaches effectively.

**Expected Outcome:**
- Enhanced security for the ezmail repository.
- Reduced risk of security vulnerabilities.
- Improved user data protection.
- Increased confidence in the project's security measures.

**Additional Information:**
Security is a top priority, especially for projects that involve user data. By setting up a security policy, we can demonstrate our commitment to protecting our users and the project itself.

**Comment by architgupta435** [comment]
I would like to work on this issue please assign this issue to me.
