### ISSUE TITLE
[Bug]:Update the logo of the twitter.

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#49]
**Description**
The logo of the twitter is chaged to 'X' so you should change the logo to the updated logo of the twitter

**Difficulty**
Easy

**To Reproduce**
1. Go to '.Website..'
2. Scroll down to '.website...'
4. See error the twitter logo

**Expected behavior**
The twitter logo should be changed to the updated logo

**Comment by sulavghimiree** [comment]
Give me this I will do it.

**Comment by sulavghimiree** [comment]
@IshaanAdarsh  Completed please Check it

**Comment by IshaanAdarsh** [comment]
> @IshaanAdarsh  Completed please Check it

Could you link the PR

**Comment by sulavghimiree** [comment]
#52 this PR solves this issue. Thanks.
@IshaanAdarsh
