### ISSUE TITLE
Add Light Mode Toggle

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#5]
Description: We aim to provide a more comfortable browsing experience for our users, especially during nighttime. To achieve this, we need to implement a Dark Mode and Light Mode feature on our website. This task involves making substantial changes to our CSS to ensure a smooth transition between the two modes. Users should be able to switch between light and dark modes effortlessly for a visually pleasing experience.

Difficulty: Hard

Tags: Enhancement, Tailwind, User Experience

**Comment by Prasanthisandaka2005** [comment]
Hello @IshaanAdarsh Can I work on this? I'm eager to take on the task of making it visually appealing to enhance the overall user experience.

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Could you please assign this issue to me
