### ISSUE TITLE
Comprehensive Update of Installation Guide

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#7]
**Description:** It's time to give our installation guide a thorough refresh to keep it aligned with recent changes in the project setup. We need meticulous contributors to ensure that every detail is up-to-date and crystal clear. The goal is to provide users with an installation process that's as smooth as possible, so they can get started hassle-free.

- **Difficulty:** Easy

- **Tags:** Documentation, Installation

**Comment by tanishk2705** [comment]
I would like to work on this issue please assign this issue to me.
