### ISSUE TITLE
Add Spell Check and Grammar Check

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#71]
**Issue Description**: Integrate a spell and grammar checking feature to help users compose error-free emails.
- **Labels**: Feature, Writing

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh could you please assign this issue to me?

**Comment by Pranav-Rustagi** [comment]
Regarding the task, should there be a new button clicking on which errors would be highlighted? Or it should automatically do it?

**Comment by IshaanAdarsh** [comment]
@Pranav-Rustagi it should automatically show errors.

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh Do you have any API recommendations for this? I tried finding out but apparently most of the solutions are either paid, or deprecated. Besides that, all API's support certain set of languages and not all.

**Comment by IshaanAdarsh** [comment]
@Pranav-Rustagi I will look around too.

**Comment by IshaanAdarsh** [comment]
@Pranav-Rustagi 
looked around and found this -> https://sqa.stackexchange.com/questions/49529/is-there-a-free-api-for-spell-and-grammar-check

https://rapidapi.com/grammarbot/api/grammarbot-neural/pricing
https://www.grammar.com/grammar_api.php

**Comment by Pranav-Rustagi** [comment]
I have found a solution to this, but it will support only English language. Should I work on it?

**Comment by IshaanAdarsh** [comment]
@Pranav-Rustagi sure go ahead.

**Comment by Pranav-Rustagi** [comment]
@IshaanAdarsh sorry for bothering. That solution only works for spell check and does not help with grammar check. I spent hours searching for free solution, but could not find any. Let me know in case you come across anything, which could evaluate grammatical errors. I'd be happy to integrate.
