### ISSUE TITLE
User Registration and Login

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#72]
### Description
- Implement the user registration and login functionality to enable users to create accounts and log in.

#### Tasks
- Create user registration forms.
- Develop the backend to handle registration and login requests.
- Implement email verification during registration.
- Ensure password security and hashing.

**Comment by Albert-2** [comment]
hey @IshaanAdarsh ....!!
I will be more than happy to contribute 
can you please explain me in which environment you want your backend to be.....
THANK YOU...!:)

**Comment by IshaanAdarsh** [comment]
I was hoping first of all make the front end using this issue and then approach the backend part of the project later. @Albert-2 you have all the creative freedom if there is any issue i will address it on my end
