### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#73]
#### Description
- Create a user profile page where users can view and edit their account details.

#### Tasks
- Design the user profile interface.
- Develop the frontend for the user profile page.
- Implement the backend to fetch and display user information.
- Add the option to edit user details.

**Comment by Manikantan-S** [comment]
@IshaanAdarsh  I can do this please assign this to me . Thanks

**Comment by professorabhay** [comment]
Hey, @IshaanAdarsh, I would like to work on this!
Kindly assign it to me.
