### ISSUE TITLE
User Sessions

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#76]
#### Description
- Implement secure user sessions to keep users logged in.

#### Tasks
- Develop session management functionality.
- Ensure session security.
- Set up session expiration mechanisms.

**Comment by Albert-2** [comment]
Hey @IshaanAdarsh ...!!
i would really like to contribute 
can you please assign me this issue
thank you for considering

**Comment by Albert-2** [comment]
authentication is done through jwt and if in case user leave the site without logging out then also the session will remain as it is
you have any other requirements which I am not getting then please tell me
thank you... ✌️
