### ISSUE TITLE
Forgot Password

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#77]
#### Description
- Add the "Forgot Password" functionality for users to reset their passwords.

#### Tasks
- Create a "Forgot Password" page.
- Implement the email-based password reset process.
- Ensure secure password reset.

**Comment by ProgrammingWithSid** [comment]
Hi Ishaan Adarsh I wanted to contribute for this feature.

**Comment by Jilesh980** [comment]
Hi Ishaan Adarsh , can i work on this issue ..!

**Comment by bhavik001** [comment]
Hello @IshaanAdarsh Can I work on this issue?
