### ISSUE TITLE
Problem with the logo at the bottom of the page

### ISSUE THREAD

**Issue by ivanosquis10** [IshaanAdarsh/ezmail#82]
It's probably something they have in mind but they have that flaw down there that makes the page look not so nice :(. I suggest you put a temporary logo or the same logo you have on the header :)

Image:
![Screenshot_20231013_122622_Chrome.png](https://github.com/IshaanAdarsh/ezmail/assets/83567373/8f87824d-1571-4a26-af7e-5c1252d56378)

**Comment by Kamleshwarpradhan** [comment]
I think I can work on this issue can you assign me?
