### ISSUE TITLE
Improve Alt Text for Images

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#9]
**Description:** Accessibility is a top priority for us, and we want to ensure that every image on our website is accompanied by descriptive and meaningful alt text. We need contributors who are committed to reviewing and updating alt text where necessary. By doing so, we can make our content accessible to a wider audience, including those who rely on screen readers.

- **Difficulty:** Easy

- **Tags:** Accessibility, Images

**Comment by bhalerao-2002** [comment]
Hello @IshaanAdarsh,
Alter Images are a great tool in terms of Accessibility for Only readers or low-end devices. Glad as a developer you are concerned about this too.
please assign this issue to me under Hacktoberfest, as I already started working on the footer, I will go through the whole code and review all Images and alt texts.

**Comment by IshaanAdarsh** [comment]
@bhalerao-2002, do you still want to do this?

**Comment by bhalerao-2002** [comment]
Yes, give me some time i Will raise PR

**Comment by pnnv** [comment]
Can I have this issue as it hasn't been claimed yet?

**Comment by SanidhayaAgarwal** [comment]
Hello @IshaanAdarsh  ,

I'm excited to participate in Hacktoberfest and contribute to this repository. Please consider me for this issue. I look forward to collaborating with the community.

Thank you!
