### ISSUE TITLE
Enhance Footer Section UI

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#91]
**Issue Description:** 
The current UI of the footer section on the EzMail website requires improvement. Enhancing the footer's visual and functional aspects will contribute to a better user experience. This issue aims to address that.

**Tasks:**
1. Improve the overall design of the footer.
2. Enhance the layout for better alignment and spacing.
3. Update the color scheme to match the website's theme.
4. Include important links or information as required.
5. Ensure responsiveness for various screen sizes.

**Additional Details:**
Please provide any additional design or content ideas that should be considered for the footer enhancement.

<img width="1428" alt="Screenshot 2023-10-16 at 10 15 55 PM" src="https://github.com/IshaanAdarsh/ezmail/assets/100434702/a66fd6b9-ee33-4ba1-bea1-d0baf0666645">

**Comment by Archit-Jain-Github** [comment]
I would like to work on the following issue kindly assign it to me

**Comment by AviralPatel0526** [comment]
![footer](https://github.com/IshaanAdarsh/ezmail/assets/135042334/11c48178-9bb7-415a-8811-fe3a742efe72)

**Comment by AviralPatel0526** [comment]
is this fine sir??

**Comment by AviralPatel0526** [comment]
pr made.
#95

**Comment by AviralPatel0526** [comment]
pr made.
#96

**Comment by AviralPatel0526** [comment]
![Screenshot 2023-10-21 222227](https://github.com/IshaanAdarsh/ezmail/assets/135042334/dbb88c55-117b-4b63-a34f-e754a8f7bbf7)

**Comment by AviralPatel0526** [comment]
is this fine sir??

**Comment by AviralPatel0526** [comment]
![Screenshot 2023-10-21 224453](https://github.com/IshaanAdarsh/ezmail/assets/135042334/aa9c9b11-c42b-4b8e-befc-d1e528dade79)
mobile view

**Comment by AviralPatel0526** [comment]
pr made
#97

**Comment by IshaanAdarsh** [comment]
Good work @AviralPatel0526.
for future, link the PR to the issue in the PR comments not the otherway around.
