### ISSUE TITLE
`To Administration` - Link Is Broken

### ISSUE THREAD

**Issue by IshaanAdarsh** [IshaanAdarsh/ezmail#99]
**Problem:** The link for "To Administration" in the footer is not working. It leads to an incorrect URL 'admn.'
- **Solution:** Correct the 'href' attribute for the "To Administration" link to "admin" to enable proper redirection to the administration page.

**Comment by anevski-stefan** [comment]
@IshaanAdarsh Can you assign me, I want to work on this issue?

**Comment by anevski-stefan** [comment]
It's done, can you please review it?

**Comment by architgupta435** [comment]
Can you please assign this issue to me
